-- Update Medical Device Development topic keywords
-- Remove generic keywords: technology, clinical trials, biomedical engineering, medical device technology
-- Add development-specific keywords: device development, device manufacturing, medtech industry, device regulation, device approval

UPDATE topics 
SET keywords = ARRAY[
  'fda approval process',
  'prototype development',
  'regulatory compliance',
  'quality management systems',
  'design controls',
  'human factors engineering',
  'sterilization validation',
  'verification and validation',
  'risk management',
  'medical device manufacturing',
  'iso 13485',
  'usability testing',
  'premarket submission',
  'supply chain optimization',
  'rfid medical technology',
  '3d printing medical implants',
  'at-home diagnostic devices',
  'surgical efficiency technologies',
  'power delivery systems',
  'spinal cord repair devices',
  'dermatology diagnostic tools',
  'medical device materials science',
  'surgical inventory management',
  'implantable medical devices',
  'point-of-care testing',
  'medical device cybersecurity',
  'biocompatibility testing',
  'medical device software validation',
  'regulatory strategy medical devices',
  'digital health technologies',
  'medical device post-market surveillance',
  'medical device innovation',
  'medical device clinical evaluation',
  'organoid technology',
  'hiv prevention technology',
  'stem cell medical applications',
  'in vitro diagnostics',
  'continuous glucose monitoring',
  'biomarker detection technology',
  'monoclonal antibody delivery systems',
  'cell therapy devices',
  'immune cell engineering devices',
  'liquid biopsy technology',
  'organ-on-chip technology',
  'medical device recall management',
  'drug delivery systems',
  'point-of-care imaging',
  'bioreactor technology',
  'medical device clinical evidence',
  'telemedicine devices',
  'medical device biocompatibility standards',
  'orthopedic implants',
  'cardiovascular devices',
  'surgical instruments',
  'diagnostic equipment',
  'prosthetic devices',
  'surgical technology',
  'patient monitoring',
  'imaging devices',
  'respiratory devices',
  'neurological devices',
  'dental devices',
  'ophthalmic devices',
  'wound care devices',
  'rehabilitation devices',
  'device development',
  'device manufacturing',
  'medtech industry',
  'device regulation',
  'device approval',
  'device commercialization',
  'device design',
  'device testing',
  'regulatory submission',
  'quality assurance',
  'device validation'
],
updated_at = now()
WHERE id = '3f05c5a3-3196-455d-bff4-e9a9a20b8615';
